/// <summary>
/// Reads the optional asset manifest generated by preprocessing scripts.
/// </summary>
internal static class OfflineAssetIndex {
	/// <summary>
	/// Loads the optional TSV index that maps online asset URLs to local files.
	/// </summary>
	public static Dictionary<string, OfflineAsset> Load(string path, string rootDirectory) {
		var map = new Dictionary<string, OfflineAsset>(StringComparer.Ordinal);
		if (!File.Exists(path)) return map;

		// TSV layout: original URL, relative file path, content type, plus metadata columns we do not need here.
		foreach (string line in File.ReadLines(path).Skip(1)) {
			if (string.IsNullOrWhiteSpace(line)) continue;

			string[] parts = line.Split('\t');
			if (parts.Length < 6) continue;

			string link = parts[0].Trim();
			string relativePath = NormalizeWorkspacePath(parts[1].Trim(), rootDirectory);
			string contentType = parts[2].Trim();

			if (!string.IsNullOrEmpty(relativePath)) {
				map[link] = new OfflineAsset(relativePath, contentType);
			}
		}

		return map;
	}

	static string NormalizeWorkspacePath(string path, string rootDirectory) {
		if (string.IsNullOrWhiteSpace(path)) return string.Empty;

		string normalized = path.Replace('\\', '/').TrimStart('/');
		bool rootedRelative = (path.StartsWith("/", StringComparison.Ordinal) && !path.StartsWith("//", StringComparison.Ordinal))
			|| (path.StartsWith("\\", StringComparison.Ordinal) && !path.StartsWith("\\\\", StringComparison.Ordinal));
		if (rootedRelative) {
			return normalized;
		}
		if (!Path.IsPathRooted(path)) return normalized;

		string fullPath = Path.GetFullPath(path);
		string rootPath = Path.GetFullPath(rootDirectory);
		if (!rootPath.EndsWith(Path.DirectorySeparatorChar)) rootPath += Path.DirectorySeparatorChar;
		if (!fullPath.StartsWith(rootPath, StringComparison.OrdinalIgnoreCase)) return string.Empty;

		return Path.GetRelativePath(rootDirectory, fullPath)
			.Replace(Path.DirectorySeparatorChar, '/')
			.Replace(Path.AltDirectorySeparatorChar, '/');
	}
}
